create table USER
(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL ,
	ACCOUNT_ID VARCHAR(100),
	NAME VARCHAR(50),
	TOKEN CHAR(36),
	AVATAR_URL VARCHAR(256),
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT,
    constraint USER_PK
    primary key (ID)
);